- contracts/core/governance/resolution/Resolvable.sol
- Resets the `claimBeginsFrom` and `claimExpiresAt` back to zero, if the incident is resolved as false.
> Set claim period correctly for any decision

- contracts/core/governance/resolution/Resolvable.sol
Update `claimBeginsFrom` such that 
- If the reporting is resolved as **Incident Occurred** then the claim period starts as soon as the resolution deadline ends.
- If the reporting is resolved as **False Reporting** then `claimBeginsFrom` is set to `0`
> Fix claimBeginsFrom timestamp

- .solcover.js
- contracts/core/policy/Policy.sol
- contracts/interfaces/IPolicy.sol
- contracts/libraries/CoverLibV1.sol
- contracts/libraries/CoverUtilV1.sol
- contracts/libraries/PolicyHelperV1.sol
- package.json
- scripts/upgrade/bond-pool.js
- test/specs/lifecycle/cover/add-cover.spec.js
- test/specs/policy/calculate-policy-fee.spec.js
- test/specs/policy/get-cxtoken-by-expiry-date.spec.js
- test/specs/policy/util/calculator.js
- test/specs/policy/util/calculator.spec.js
- test/stories/1. policy.spec.js
- util/helper.js
- Added a new function `calculatePolicyFee` to replace `getCoverFee`
- Refactored helper util
- Replaced `getCoverFeeInfo` logic with `calculatePolicyFee` and dropped the latter
- Dropped obsolete arg `coverRatio` from `getCoverFeeInfo`
- Renamed `getCoverFee` to `getCoverCreationFeeInfo` for added clarity
- Dropped unused function `getCoverFeeInfoInternal`
- Renamed `getCoverFeeInternal` to `getPolicyFeeInternal`
- Refactored and added tests
> Refactoring Policy Fee Calculation

- contracts/core/governance/Reporter.sol
- contracts/core/governance/resolution/Resolvable.sol
- contracts/core/governance/resolution/Unstakable.sol
- contracts/libraries/ValidationLibV1.sol
- test/specs/governance/attest.spec.js
- test/specs/governance/deps.js
- test/specs/governance/dispute.spec.js
- test/specs/governance/emergency-resolve.spec.js
- test/specs/governance/finalize.spec.js
- test/specs/governance/get-resolution-date.spec.js
- test/specs/governance/refute.spec.js
- test/specs/governance/report.spec.js
- test/specs/governance/resolution/configure-cool-down-period.spec.js
- test/specs/governance/resolution/deps.js
- test/specs/governance/resolution/get-cool-down-period.spec.js
- test/specs/governance/resolution/get-resolution-deadline.spec.js
- test/specs/governance/resolution/get-unstake-info-for.spec.js
- test/specs/governance/resolution/unstake-with-claim.spec.js
- test/specs/governance/resolution/unstake.spec.js
- test/specs/governance/resolve.spec.js
- Fixed a bug in governance `unstake` feature which allows user to invoke `unstake` even before the incident resolved.
- Fixed a bug in governance `unstakeWithClaim` feature which allows user to invoke `unstakeWithClaim` even after the claim period is ended (before finalized).
- Added tests for the above fixes.
> Fixed reporting `unstake` and added tests

- contracts/core/delegates/VaultDelegateBase.sol
- contracts/core/liquidity/LiquidityEngine.sol
- contracts/core/liquidity/strategies/AaveStrategy.sol
- contracts/core/liquidity/strategies/CompoundStrategy.sol
- contracts/fakes/FakeCompoundDaiDelegator.sol
- contracts/fakes/FaultyAaveLendingPool.sol
- contracts/fakes/FaultyCompoundDaiDelegator.sol
- contracts/fakes/InvalidStrategy.sol
- contracts/interfaces/ILiquidityEngine.sol
- contracts/libraries/PriceLibV1.sol
- contracts/libraries/StrategyLibV1.sol
- test/specs/liquidity/engine/add-strategies.spec.js
- test/specs/liquidity/engine/disable-strategy.spec.js
- test/specs/liquidity/engine/set-lending-periods-default.spec.js
- test/specs/liquidity/engine/set-lending-periods.spec.js
- test/specs/liquidity/strategy/aave/ctor.spec.js
- test/specs/liquidity/strategy/aave/deposit.spec.js
- test/specs/liquidity/strategy/aave/drain.spec.js
- test/specs/liquidity/strategy/aave/withdraw.spec.js
- test/specs/liquidity/strategy/compound/ctor.spec.js
- test/specs/liquidity/strategy/compound/deposit.spec.js
- test/specs/liquidity/strategy/compound/drain.spec.js
- test/specs/liquidity/strategy/compound/withdraw.spec.js
- test/specs/liquidity/strategy/deps.js
- test/specs/recoverable/token.spec.js
- util/composer/fakes.js
- Added a check on strategy withdrawal to ensure that redeeming aTokens or cTokens results in stablecoin withdrawals
- Added `getLendingPeriods` to `ILiquidityEngine`
- Refactored `getLendingPeriodKey` and `getWithdrawalWindowKey` on StrategyLibV1 to drop `ignoreMissingKey` check
- Added more tests to increase coverage
> Liquidity Tests

- contracts/core/delegates/VaultDelegateWithFlashLoan.sol
- contracts/core/lifecycle/CoverStake.sol
- contracts/core/liquidity/WithFlashLoan.sol
- contracts/core/policy/Policy.sol
- contracts/mock/MockFlashBorrower.sol
- test/specs/lifecycle/cover-stake/increase-stake.spec.js
- test/specs/liquidity/vault/flashloan.spec.js
- Refactored `increaseStake` function to use `ensureTransfer` instead of `ensureTransferFrom` when transferring out of the same contract
- Added test case of fee burning
> Cover Stake Coverage

- contracts/core/delegates/VaultDelegateBase.sol
- contracts/libraries/CoverUtilV1.sol
- contracts/libraries/ProtoUtilV1.sol
- contracts/libraries/VaultLibV1.sol
- Refactored the codebase to drop maintaining individual account's liquidity added and removed states because you are now allowed to transfer PODs to a different wallet address and claim using that address.
- As a result of the above `_redeemPods` function now doesn't need to update the state and therefore the function name is changed to `_redeemPodCalculation` to signify that it is a read-only function or a view
> POD Fungibility Refactor

- contracts/core/delegates/VaultDelegateBase.sol
- contracts/core/token/NPM.sol
- contracts/libraries/RoutineInvokerLibV1.sol
- test/specs/liquidity/vault/add-liquidity.spec.js
- test/specs/liquidity/vault/deps.js
- test/specs/liquidity/vault/remove-liquidity.spec.js
- test/specs/token/npm.spec.js
- Added new features `issueMany` and `transferMany` to NPM token
- Split the functions `_executeIsWithdrawalPeriod` to two: `_isWithdrawalPeriod` and `_updateWithdrawalPeriod`.
- The `_updateWithdrawalPeriod` period still works without any strategy being present.
- Fixed mistake in documentation of `getInfoImplementation` in `VaultDelegateBase`
- Added more test cases
> Refactored NPM Token and Routine Invoker

- contracts/core/store/StoreBase.sol
- contracts/libraries/BaseLibV1.sol
- test/bdd/fractionalization.js
- test/specs/recoverable/token.spec.js
- test/specs/store/recoverable.spec.js
The recoverable contract enables protocol admins to recover accidentally-sent ERC20 tokens to the Neptune Mutual protocol contracts.
https://docs.neptunemutual.com/usage/recovering-cryptocurrencies
This pull request helps maintain compatibility with some tokens which do not properly return a boolean value to indicate the transfer state by dropping the require statements on the return value of IERC20.transfer.
> Removed ERC-20 Force Transfers

- contracts/core/lifecycle/Cover.sol
Dropped the redundant and wrong check `AccessControlLibV1.mustBeCoverManager(s)`
> Updated ACL on `updateCoverUsersWhitelist`

- contracts/libraries/GovernanceUtilV1.sol
Dropped unused and redundant statement on the function `getReportingUnstakenAmountInternal`.
> Refactored `getReportingUnstakenAmountInternal`

- contracts/core/lifecycle/CoverStake.sol
- contracts/interfaces/ICoverStake.sol
- contracts/libraries/CoverLibV1.sol
- contracts/libraries/CoverUtilV1.sol
- contracts/libraries/ProtoUtilV1.sol
- util/ipfs.js
- Persisted the cover creation timestamp when a new cover is created
- Refactored the `decreaseStake` function to make it publicly accessible
- Cover creators can optionally withdraw their full stake after 365 days of cover creation
- Refactored events `StakeAdded` and `StakeRemoved` to add “account” argument
> Fixed `decreaseStake` issue

- contracts/libraries/VaultLibV1.sol
- test/specs/liquidity/vault/deps.js
- test/specs/liquidity/vault/remove-liquidity.spec.js
Only allow to exit if liquidity provider can unstake all of their NPM
> Fixed withdrawal of liquidity stake while exit

- contracts/libraries/RoutineInvokerLibV1.sol
- scripts/config/network/mainnet.js
- Fixed calculation of `_canDeposit` amount to consider the amount of stablecoin already lent out to the strategies.
- Decreases the `stateUpdateInterval` time to 1 hour on `mainnet` so that token prices, withdrawal window are updated every one hour
> Fix state update interval and  calculation of deposit amount for lending

- contracts/core/liquidity/LiquidityEngine.sol
- contracts/interfaces/ILiquidityEngine.sol
- contracts/libraries/StrategyLibV1.sol
- contracts/libraries/ValidationLibV1.sol
- Added `deleteStrategy` feature in the `LiquidityEgnine` contract
- Updated `callerMustBeStrategyContract` to accept both active and disabled strategies
> Withdraw from Disabled

- contracts/core/liquidity/VaultLiquidity.sol
- removed `podsToRedeem > 0` requirement check from `removeLiquidity` function in `VaultLiquidity`
- ensure either `podsToRedeem` or `npmStakeToRemove` is greater than 0
> Updated `removeLiquidity` function in `VaultLiquidity`

- contracts/core/Protocol.sol
- test/specs/protocol/grant-role.spec.js
- Fixes #142
- Overridden the inherited `grantRole` function so that any role is not granted when protocol is paused
> Fixes Issue #142 - Parallel access control 

- contracts/core/governance/resolution/Finalization.sol
- contracts/core/governance/resolution/Resolvable.sol
- contracts/interfaces/IResolvable.sol
- test/specs/governance/close-report.spec.js
- The `closeReport` feature allows Governance Admin to emergency resolve an incident when the incident which is reported is a **False Reporting**. This will help to reduce the spam incident reports in the protocol. #117
> Added a feature to close a report

- contracts/core/Protocol.sol
- test/examples/distributor/add-liquidity.spec.js
- test/examples/distributor/get-premium.spec.js
- test/examples/distributor/purchase-policy.spec.js
- test/examples/distributor/remove-liquidity.spec.js
- test/specs/libraries/access-control.spec.js
- test/specs/libraries/cover-util.spec.js
- test/specs/libraries/routine-invoker.spec.js
- test/specs/libraries/store-key-util.spec.js
- test/specs/libraries/vault.spec.js
- test/specs/liquidity/strategy/aave/deposit.spec.js
- test/specs/liquidity/strategy/aave/drain.spec.js
- test/specs/liquidity/strategy/aave/withdraw.spec.js
- test/specs/liquidity/strategy/compound/deposit.spec.js
- test/specs/liquidity/strategy/compound/drain.spec.js
- test/specs/liquidity/strategy/compound/withdraw.spec.js
- test/specs/liquidity/vault/receive-from-strategy.spec.js
- test/specs/liquidity/vault/transfer-to-strategy.spec.js
- test/specs/protocol/ctor-vfns.spec.js
- util/extract/keys/template-ts.js
Dropped the protocol deployer as a member when the protocol is initialized for the first time.
> Drop Deployer as Member

- contracts/libraries/StakingPoolLibV1.sol
- Fixes #134
- Refactored `calculateRewardsInternal` to consider the reward token of the pool with given `key` instead of the reward token balance of `StakingPools.sol` contract
> Fixes Issue #134 - Conflated staking pool reward balances

- contracts/core/governance/resolution/Finalization.sol
- contracts/libraries/GovernanceUtilV1.sol
- contracts/libraries/ProtoUtilV1.sol
- contracts/libraries/ValidationLibV1.sol
- test/specs/governance/resolution/unstake-with-claim.spec.js
- test/specs/governance/resolution/unstake.spec.js
Fix the error which disallowed winning camp to unstake their NPM after finalization
If the incident report is resolved as "incident occurred", then after the resolution deadline the winning camp can
- `unstakeWithClaim` before finalization
- `unstake` after finalization
If the incident report is resolved as "false reporting", then after the resolution deadline the winning camp can
- `unstakeWithClaim` before finalization
- `unstake` after finalization
> Fix unstake after finalization

- contracts/pool/Staking/StakingPoolBase.sol
Refactored the function `closePool` to ensure the stakers can withdraw their stakes before it can be closed.
> Fixes Issue #144 - Able to close non-empty staking pool

- contracts/interfaces/IStakingPools.sol
- contracts/pool/Staking/StakingPoolBase.sol
Added `stakingTarget` to the event `PoolUpdated`
> Fixes Issue #150 - Missing event parameter

- contracts/libraries/ProtoUtilV1.sol
- test/stories/1. policy.spec.js
Updated thresholds to 10 million - `MAX_LIQUIDITY`, `MAX_PROPOSAL_AMOUNT` and `MAX_NPM_STAKE`
> Fixes Issue #148 - Incorrect NPM threshold

- contracts/libraries/VaultLibV1.sol
Refactored the function `getInfoInternal` of the `VaultLibV1` contract to correctly use the number of PODs when calculating the caller's share of LP stablecoin balance.
> Fixes Issue #154 - Incorrect individual liquidity share

- contracts/libraries/RoutineInvokerLibV1.sol
- contracts/libraries/StakingPoolLibV1.sol
- contracts/libraries/ValidationLibV1.sol
- contracts/libraries/VaultLibV1.sol
- Refactored `mustBeDuringWithdrawalPeriod` to consider the `end` timestamp to be part of the withdrawal period
- Refactored `withdrawInternal` to allow withdrawals on block height where withdrawals can start
- Refactored `mustBeAfterResolutionDeadline` to succeed on the resolution deadline timestamp
- Refactored `getFlashFeesInternal` to allow lending of whole stablecoin balance of the vault
Fixes #147
> Fixes Issue #147 - Imprecise bounds

- contracts/core/Protocol.sol
- Removed redundant pause check on the Protocol contract
- Closes #131 
- Closes #169
> Fixes Issue #169 - Repeated pause validation

- contracts/core/governance/Reporter.sol
- contracts/core/lifecycle/Cover.sol
- contracts/interfaces/ICover.sol
- contracts/interfaces/IReporter.sol
- contracts/libraries/CoverLibV1.sol
- contracts/libraries/StoreKeyUtil.sol
- util/composer/covers.js
- util/ipfs.js
- Refactored all instances of `IPFS info` object to use `string` instead of `bytes32`
- Moved the IPFS info length validation to `_addCover` from `_validateAndGetFee`
- Renamed the function `_validateAndGetFee` to `_getFee`
- Refactored JavaScript test helper modules to plain IPFS hash
> Fixes Issue #153 - The info parameter might lose information about an IPFS hash

- contracts/pool/Bond/BondPoolBase.sol
- contracts/pool/Staking/StakingPoolBase.sol
- Replaced `admin` with `liquidity manager` on `addOrEditPool` and `closePool` functions of the StakingPoolBase contract.
- Replaced `admin` with `liquidity manager` on `setup` function of the BondPoolBase contract.
> Fixes Issue #152 - Protocol administrator needs to handle external tokens

- contracts/core/ProtoBase.sol
Removed duplicate `whenPaused` modifier on the `unpause` function of the `ProtoBase` contract
> Fixes Issue #176 - Duplicate modifier

- contracts/libraries/GovernanceUtilV1.sol
- Replaced `msg.sender` with parameter `who` in `addRefutationInternal` and `addAttestationInternal`
> Fixes Issue #182 - Unnecessary coupling

- contracts/core/store/StoreBase.sol
- contracts/core/token/WithRecovery.sol
- contracts/libraries/BaseLibV1.sol
- Replaced transfer calls with`address.call{value: amount}("")` to send ether
> Fixes Issue #174 - transfer and send calls are no longer considered best practice
