neptune-mutual-blue/protocol

contracts/core/liquidity/VaultBase.sol, contracts/interfaces/IVault.sol, contracts/libraries/ProtoUtilV1.sol, contracts/libraries/RoutineInvokerLibV1.sol, contracts/libraries/StrategyLibV1.sol, contracts/libraries/VaultLibV1.sol, hardhat.config.js, test/protocol.spec.js, util/composer/libs.js, util/composer/vault.js
- Moved vault strategy logic from VaultLibV1 to StrategyLibV1 to reduce the deployment size
- Fixed the accounting errors of lent out amount and received amounts for any given strategy
- Fixed the bug in total amount in strategies
- Refactored tests
=> Refactor Strategy

test/specs/cx-token/burn.spec.js, test/specs/cx-token/mint.spec.js, test/specs/protocol/add-contract.spec.js, test/specs/protocol/setup-role.spec.js, test/stories/2. governance.spec.js
Implemented tests for setting up role and admin
=> Setup Role Tests

contracts/interfaces/IStakingPools.sol, contracts/libraries/StakingPoolCoreLibV1.sol, contracts/libraries/StakingPoolLibV1.sol, contracts/pool/Staking/StakingPoolBase.sol, contracts/pool/Staking/StakingPoolReward.sol, package.json, test/specs/pool/staking/add-or-edit-pool.spec.js, test/specs/pool/staking/close-pool.spec.js, test/specs/pool/staking/ctor-vfns.spec.js, test/specs/pool/staking/deposit.spec.js, test/specs/pool/staking/deps.js, test/specs/pool/staking/withdraw-rewards.spec.js, test/specs/pool/staking/withdrawal.spec.js, util/block.js
- Refactored `getName` of StakingPoolBase to return correct contract name
- Added constructor and view function tests
=> Staking Pool Tests

contracts/core/policy/PolicyAdmin.sol, contracts/libraries/PolicyHelperV1.sol, test/specs/policy-admin/ctor.spec.js, test/specs/policy-admin/deps.js, test/specs/policy-admin/set-policy-rates-by-key.spec.js, test/specs/policy-admin/set-policy-rates.spec.js, test/specs/policy/ctor.spec.js, test/specs/policy/deps.js, test/specs/policy/get-cxtoken-by-expiry-date.spec.js, test/specs/policy/purchase-cover.spec.js, test/specs/pool/bond/calculate-tokens-for-lp.spec.js, test/specs/pool/bond/claim-bond.spec.js, test/specs/pool/bond/create-bond.spec.js, test/specs/pool/bond/npm-token-price.spec.js, test/specs/pool/bond/setup.spec.js
- Refactored `setPolicyRatesByKey` to ensure only valid cover keys are accepted.
- Refactored error message for consitency
- Fixed a bug in `getPolicyRatesInternal`
- Added tests and coverage
- Fixed Javascript Standard issues
=> Policy and Policy Admin Tests

contracts/interfaces/ILiquidityEngine.sol, contracts/libraries/StrategyLibV1.sol, test/specs/governance/deps.js, test/specs/governance/resolution/ctor.spec.js, test/specs/governance/resolution/deps.js, test/specs/governance/set-first-reporting-stake.spec.js, test/specs/governance/set-reporter-burn-rate.spec.js, test/specs/governance/set-reporter-commission.spec.js, test/specs/lifecycle/cover/add-cover.spec.js, test/specs/lifecycle/cover/ctor-vfns.spec.js, test/specs/lifecycle/cover/deps.js, test/specs/lifecycle/cover/stop-cover.spec.js, test/specs/lifecycle/cover/update-cover-creator-whitelist.spec.js, test/specs/lifecycle/cover/update-cover-users-whitelist.spec.js, test/specs/lifecycle/cover/update-cover.spec.js, test/specs/liquidity/engine/deps.js, test/specs/liquidity/engine/set-lending-periods-default.spec.js, test/specs/liquidity/engine/set-lending-periods.spec.js, test/specs/liquidity/vault/ctor.spec.js, test/specs/liquidity/vault/deps.js, test/specs/liquidity/vault/flash-loan.spec.js, test/specs/policy-admin/set-policy-rates-by-key.spec.js, test/specs/policy/purchase-cover.spec.js
- Emit `LendingPeriodSet` event when lending period is updated
- Added more tests to cover, governance and liquidity contracts
- Avoid using `ipfs.write()` for tests
=> Refactor & Added tests for governance and liquidity features

contracts/fakes/ForceEther.sol, test/bdd/fractionalization.js, test/specs/token/delayable.spec.js, test/specs/token/npm.spec.js, test/specs/token/recoverable.spec.js
- Added a new contract `ForceEther`
- Added tests for delayable, recoverable, and NPM
- Fixed failing fractionalization tests
=> Added NPM Token Unit Tests

test/specs/claims-processor/claim.spec.js, test/specs/claims-processor/ctor-vfns.spec.js, test/specs/claims-processor/set-claim-period.spec.js, test/specs/claims-processor/validate.spec.js, test/specs/cx-token/before-token-transfer.spec.js, test/specs/cx-token/burn.spec.js, test/specs/cx-token/ctor-vfns.spec.js, test/specs/governance/set-reporter-burn-rate.spec.js, test/specs/lifecycle/cover/add-cover.spec.js, test/specs/lifecycle/cover/stop-cover.spec.js, test/specs/lifecycle/cover/update-cover-users-whitelist.spec.js, test/specs/lifecycle/cover/update-cover.spec.js, test/specs/liquidity/vault-factory/ctor.spec.js, test/specs/protocol/add-contract.spec.js, test/specs/protocol/add-member.spec.js, test/specs/protocol/ctor-vfns.spec.js, test/specs/protocol/pause.spec.js, test/specs/protocol/remove-member.spec.js, test/specs/protocol/setup-role.spec.js, test/specs/protocol/unpause.spec.js, test/specs/protocol/upgrade-contract.spec.js
Refactored tests to optimize speed
=> Refactored Tests

.solcover.js, contracts/libraries/StakingPoolCoreLibV1.sol, contracts/libraries/StakingPoolLibV1.sol, test/specs/pool/staking/add-or-edit-pool.spec.js, test/specs/pool/staking/deposit.target.achieved.spec.js, test/specs/pool/staking/withdrawal.spec.js, test/specs/pool/staking/zero-reward.spec.js
- Refactored and added more tests to complet the code coverage of staking pool contract and libraries
- Refactored `.solcover.js` to ignore `mock` folder
=> Staking Pool Code Coverage

contracts/libraries/BondPoolLibV1.sol, test/specs/pool/bond/claim-bond.spec.js, test/specs/pool/bond/create-bond.spec.js, test/specs/pool/bond/setup.spec.js
- Refactored and added more tests to complet the code coverage of bond pool contract and libraries
- Refactored `createBondInternal` of BondPoolLibV1 to remove redundant `minNpmDesired` validation
=> Bond Pool Code Coverage

contracts/core/lifecycle/CoverReassurance.sol, contracts/interfaces/ICoverReassurance.sol, test/specs/cx-token-factory/ctor.spec.js, test/specs/cx-token-factory/deps.js, test/specs/lifecycle/cover-provision/ctor-vfns.spec.js, test/specs/lifecycle/cover-provision/deps.js, test/specs/lifecycle/cover-reassurance/ctor-vfns.spec.js, test/specs/lifecycle/cover-reassurance/deps.js, test/specs/lifecycle/cover-reassurance/get-reassurance.spec.js, test/specs/lifecycle/cover-reassurance/set-weight.spec.js, test/specs/lifecycle/cover-stake/ctor-vfns.spec.js, test/specs/lifecycle/cover-stake/deps.js, test/specs/lifecycle/cover/set-cover-fees.spec.js, test/specs/lifecycle/cover/set-min-cover-creation-stake.spec.js, test/specs/lifecycle/cover/set-min-stake-to-add-liquidity.spec.js, test/specs/lifecycle/cover/update-cover.spec.js
- Added `WeightSet` event to CoverReassurance contract
- Added more tests
=> Added tests to cover lifecycle contracts

test/bdd/fractionalization.js, test/specs/liquidity/strategy/deps.js, util/demo-data/add-liquidity.js, util/demo-data/purchase-policy.js
Fixed test errors because of `Vault.addLiquidity` signature change
=> Fixed Test Errors

contracts/core/policy/Policy.sol, contracts/interfaces/IPolicy.sol
Added an incrementable state variable called `lastPolicyId` emitted upon cover purchase(s)
=> Added Policy ID

contracts/core/delegates/VaultDelegateWithFlashLoan.sol, contracts/core/liquidity/WithFlashLoan.sol, contracts/core/policy/Policy.sol, contracts/mock/MockFlashBorrower.sol, test/specs/liquidity/vault/flashloan.spec.js
- Refactored flash loan feature to remove redundant address and amount validation
- Refactored flash loan feature to transfer protocol commission after all checks are passed
- Fixed a typo in Policy contract
- Completed flash loan coverage
=> Flash Loan Coverage

test/specs/liquidity/engine/set-liquidity-state-update-interval.spec.js, test/specs/liquidity/vault/add-liquidity.spec.js, test/specs/liquidity/vault/calculate-liquidity.spec.js, test/specs/liquidity/vault/calculate-pods.spec.js, test/specs/liquidity/vault/get-info.spec.js, test/specs/liquidity/vault/remove-liquidity.spec.js
- Added tests for vault and liquidity engine contracts
=> Added tests for vault contracts

contracts/mock/lib-user/MockAccessControlUser.sol, test/specs/libraries/access-control.spec.js, test/specs/libraries/deps.js, test/specs/liquidity/vault/receive-from-strategy.spec.js, test/specs/liquidity/vault/transfer-to-strategy.spec.js, test/specs/policy/purchase-cover.spec.js
- Created a mock contract which uses `AccessControlLibV1` and added tests
=> Added tests for `AccessControlLibV1`

contracts/mock/lib-user/MockStoreKeyUtilUser.sol, contracts/mock/lib-user/MockValidationLibUser.sol, test/specs/governance/finalize.spec.js, test/specs/governance/resolution/unstake-with-claim.spec.js, test/specs/libraries/deps.js, test/specs/libraries/store-key-util.spec.js, test/specs/libraries/validation.spec.js
- Added tests for StoreKeyUtil and ValidationLibV1 libraries
- Added tests for unstakeWithClaim if resolved as false reporting
=> Added tests to StoreKeyUtil and ValidationLibV1

contracts/core/delegates/VaultDelegateBase.sol, contracts/core/token/NPM.sol, contracts/libraries/RoutineInvokerLibV1.sol, contracts/mock/lib-user/MockAccessControlUser.sol, contracts/mock/lib-user/MockStoreKeyUtilUser.sol, contracts/mock/lib-user/MockValidationLibUser.sol, test/specs/governance/finalize.spec.js, test/specs/governance/resolution/unstake-with-claim.spec.js, test/specs/libraries/access-control.spec.js, test/specs/libraries/deps.js, test/specs/libraries/store-key-util.spec.js, test/specs/libraries/validation.spec.js, test/specs/liquidity/vault/add-liquidity.spec.js, test/specs/liquidity/vault/deps.js, test/specs/liquidity/vault/receive-from-strategy.spec.js, test/specs/liquidity/vault/remove-liquidity.spec.js, test/specs/liquidity/vault/transfer-to-strategy.spec.js, test/specs/policy/purchase-cover.spec.js, test/specs/token/npm.spec.js
**Smart Contract Changes**
- Added new features `issueMany` and `transferMany` to NPM token
- Split the functions `_executeIsWithdrawalPeriod` to two: `_isWithdrawalPeriod` and `_updateWithdrawalPeriod`.
- The _updateWithdrawalPeriod period works without any strategy being present.
- Fixed mistake in documentation of `getInfoImplementation` in VaultDelegateBase
**Other Changes**
- Added more test cases
=> Merge develop to autit/freeze

contracts/mock/lib-user/MockStoreKeyUtilUser.sol, test/specs/libraries/store-key-util.spec.js
Added tests and fully covered `StoreKeyUtil` library
=> Added tests for `StoreKeyUtil` library

contracts/core/store/Store.sol, contracts/libraries/PriceLibV1.sol, contracts/libraries/RoutineInvokerLibV1.sol, contracts/mock/lib-user/MockAccessControlUser.sol, contracts/mock/lib-user/MockCoverUtil.sol, contracts/mock/lib-user/MockValidationLibUser.sol, contracts/mock/lib-user/MockVaultLibUser.sol, test/specs/libraries/access-control.spec.js, test/specs/libraries/cover-util.spec.js, test/specs/libraries/deps.js, test/specs/libraries/validation.spec.js, test/specs/libraries/vault.spec.js, test/specs/liquidity/vault/remove-liquidity.spec.js, test/specs/liquidity/vault/transfer-governance.spec.js
- Added tests for libraries
- Added coverKey to the key for "last updated" timestamp for `updateStateAndLiquidity`. So that the unlock cycle will get updated more frequently.
=> Added more tests

contracts/libraries/CoverLibV1.sol
Added validation checks to `addCover` function
=> Validations for `addCover`

contracts/core/liquidity/VaultLiquidity.sol
Added the missing functionality of burning PODs whenever liquidity is removed.
=> Burn PODs While Removing Liquidity

contracts/core/delegates/VaultDelegateBase.sol, contracts/libraries/CoverUtilV1.sol, contracts/libraries/ProtoUtilV1.sol, contracts/libraries/VaultLibV1.sol
Implemented a block height offset feature so that there is a distance of at least a couple of blocks between deposits and withdrawals.
=> Vault Block Height Offset

contracts/core/store/StoreBase.sol, contracts/libraries/BaseLibV1.sol
Refactored `StoreBase` and `BaseLibV1` to use `safeTransfer` for the recovery feature.
=> Safe Transfer

.github/workflows/build.yml, .gitignore, contracts/core/lifecycle/Cover.sol, test/examples/distributor/deps.js, test/specs/cx-token-factory/deps.js, test/specs/cx-token/deps.js, test/specs/governance/deps.js, test/specs/governance/resolution/deps.js, test/specs/libraries/deps.js, test/specs/lifecycle/cover-reassurance/deps.js, test/specs/lifecycle/cover-stake/deps.js, test/specs/lifecycle/cover/ctor-vfns.spec.js, test/specs/lifecycle/cover/deps.js, test/specs/lifecycle/cover/initialize.spec.js, test/specs/lifecycle/cover/update-cover.spec.js, test/specs/lifecycle/cover/update-product.spec.js, test/specs/liquidity/delegates/deps.js, test/specs/liquidity/strategy/deps.js, test/specs/liquidity/vault/deps.js, test/specs/policy-admin/deps.js, test/specs/policy/calculate-policy-fee.spec.js, test/specs/policy/deps.js, test/specs/pool/bond/deps.js, test/stories/5.coverage.claim.spec.js, util/composer/initializer.js
Refactored the Cover contract to restrict cover and product updates during withdrawal period. Changed the role from cover owner or admin to cover manager.
=> Updating Cover and Product

contracts/core/delegates/VaultDelegateBase.sol, contracts/core/delegates/VaultDelegateWithFlashLoan.sol, contracts/core/governance/Witness.sol, contracts/core/governance/resolution/Finalization.sol, contracts/core/governance/resolution/Resolvable.sol, contracts/core/lifecycle/Cover.sol, contracts/core/lifecycle/CoverStake.sol, contracts/core/liquidity/VaultFactory.sol, contracts/core/policy/Policy.sol, contracts/libraries/CoverUtilV1.sol, contracts/libraries/GovernanceUtilV1.sol, contracts/libraries/RoutineInvokerLibV1.sol, contracts/libraries/ValidationLibV1.sol, contracts/mock/claims-processor/MockProcessorStore.sol, test/specs/claims-processor/validate.spec.js, test/stories/2. governance.spec.js, util/helper.js
- Removed `getCoverStatusInternal` and added `isCoverNormalInternal` to check all the products of a diversified cover.
=> Fix cover status

contracts/core/Protocol.sol, contracts/core/cxToken/cxToken.sol, contracts/libraries/ProtoUtilV1.sol
Note: this branch was a branch out of feature/basket-cover
- fixed the accuray of upgradeContractWithKey function
=> Fix accuracy of upgradeContractWithKey 

contracts/core/lifecycle/Cover.sol, contracts/core/liquidity/VaultLiquidity.sol, test/specs/liquidity/vault/remove-liquidity.spec.js
- Added tests to remove liquidity function
- Fix a typo
- Fix lint error for require statement
=> Added tests to remove liquidity

test/bdd/fractionalization.js, test/specs/liquidity/vault/receive-from-strategy.spec.js, test/specs/liquidity/vault/transfer-to-strategy.spec.js
- fix undefined protocol member
- timeout adjustment
=> Testing - fix undefined protocol member

contracts/core/Protocol.sol, contracts/core/Recoverable.sol, contracts/core/claims/Processor.sol, contracts/core/cxToken/cxToken.sol, contracts/core/cxToken/cxTokenFactory.sol, contracts/core/delegates/VaultDelegateBase.sol, contracts/core/delegates/VaultDelegateWithFlashLoan.sol, contracts/core/governance/Reporter.sol, contracts/core/governance/Witness.sol, contracts/core/governance/resolution/Resolvable.sol, contracts/core/governance/resolution/Unstakable.sol, contracts/core/lifecycle/Cover.sol, util/extract/keys/template-ts.js
Fix for this Issue link: https://github.com/neptune-mutual-blue/protocol/issues/120
NOTE: The changes mention bellow are all referring to its function's documentation and not the function itself
1. contracts/core/Protocol.sol 
- add params for `addContract`, `upgradeContract` and `grantRoles` functions
2. contracts/core/Recoverable.sol
- include `sendTo` as params for `recoverEther` and `recoverToken` functions
3. contracts/core/claims/Processor.sol
- Duplicate `coverKey` params on `isBlacklisted` function. Changed the other to `productKey`
4. contracts/core/cxToken/cxToken.sol
- include `productKey` as params for `mint ` function
- include `date ` as params for `_getEOD ` function 
5. contracts/core/cxToken/cxTokenFactory.sol
- include `tokenName ` as params for `deploy ` function 
6. …
=> chore: update documentations of a couple of functions

contracts/core/lifecycle/Cover.sol, util/extract/keys/template-ts.js
- For, updating the whitelist, check if the sender is **Cover Manager** instead of **Governance Agent**
- For, disabling the policy, check if the sender is **Cover Manager** instead of **Governance Admin**
=> Fix Cover contract ACL requirements

test/specs/governance/close-report.spec.js, test/specs/libraries/cover-util.spec.js, test/specs/lifecycle/cover-reassurance/add-reassurance.spec.js, test/specs/pool/staking/add-or-edit-pool.spec.js, test/specs/pool/staking/close-pool.spec.js, test/specs/pool/staking/deposit.spec.js, test/specs/protocol/pause.spec.js, test/stories/0. setup.spec.js, util/demo-data/add-reassurance.js
=> Fixed Tests

contracts/core/cxToken/cxToken.sol, contracts/libraries/PolicyHelperV1.sol, test/examples/distributor/deps.js, test/specs/cx-token-factory/deps.js, test/specs/cx-token/deps.js, test/specs/governance/deps.js, test/specs/governance/resolution/deps.js, test/specs/libraries/deps.js, test/specs/lifecycle/cover-reassurance/deps.js, test/specs/lifecycle/cover-stake/deps.js, test/specs/lifecycle/cover/deps.js, test/specs/liquidity/delegates/deps.js, test/specs/liquidity/strategy/deps.js, test/specs/liquidity/vault/deps.js, test/specs/policy/calculate-policy-fee.spec.js, test/specs/policy/deps.js, util/composer/libs.js, util/cxToken.js
- Refactored `calculatePolicyFeeInternal` to account for coverage lag period
=> Fixes Issue #141 - Incorrect policy fee

test/specs/policy/calculate-policy-fee.spec.js
Fixed the failing test `Policy: getCoverFeeInfo`
=> Fixes Failing Test

contracts/libraries/CoverLibV1.sol, contracts/libraries/StrategyLibV1.sol
- Removed unnecessary type casting
- Simplified condition
=> Fixes Issue #181 - Unnecessary complex code

contracts/core/governance/resolution/Finalization.sol
- Removed deletion of unused record
- Delete first disputer during finalization
=> Fixes Issue #178 - Incomplete deletion

contracts/core/Protocol.sol, contracts/core/governance/resolution/Finalization.sol, contracts/libraries/AccessControlLibV1.sol
- Fixed documentation of `addMember` on the `Protocol` contract
- Fixed documentation of `_finalize` on the `Finalization` contract
- Fixed documentation of `callerMustBe...` and `_mustHaveAccess` of the `AccessControlLibV1` library
=> Fixes Issue #180 - Misleading comments

examples/index.js, util/composer/covers.js, util/composer/initializer.js, util/composer/pod-staking.js, util/demo-data/add-liquidity.js, util/demo-data/add-reassurance.js, util/demo-data/purchase-policy.js
- Dropped dedicated covers examples and refactored imports
- Refactored the `createCovers` function and added stablecoin approvals to the cover contract
=> Fixed Deployment Issues

scripts/config/network/hardhat-fork.js, scripts/covers/dedicated/binance.js, scripts/covers/dedicated/okx.js, scripts/covers/deployments/binance.js, scripts/covers/deployments/okx.js
- Refactored hardhat fork network with Ethereum network config
- Fixed spacing issues of Binance and OKX covers
- Refactored Binance and OKX deployment to check allowance before sending approval transaction
=> Refactored Approvals

contracts/core/token/WithPausability.sol, test/specs/token/npm.spec.js
- Added `setPausers` function to add or remove pausers
- Refactored the `pause` function to be accessible to a pauser
- Refactored tests
=> Added Pauser Feature to token

contracts/core/lifecycle/CoverUpdate.sol, contracts/fakes/FakeStore.sol, hardhat.config.js, test/specs/policy-admin/set-coverage-lag.spec.js, test/specs/token/treasury.spec.js, util/composer/initializer.js
- Fixed failing tests
- Minor refactors in CoverUpdate.sol
=> Minor fixes and refactors
